#!/bin/sh

# Export Wakapi data to Solidtime (dry run)
./run export-wakapi-to-solidtime \
    # --solidtime-url "https://your-solidtime-instance.com" \
    # --solidtime-key "your-api-key-here" \
    # --solidtime-organization-id "your-org-id-here" \
    --wakapi-db-file "./data/wakapi.db" \
    --from "2025-06-01" \
    --to "2025-06-09" \
    --dry-run
